server:
  port: 9999

spring:
  application:
    name: love
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/love
    username: postgresql
    password: postgresql