server:
  port: 9999

spring:
  application:
    name: love
  datasource:
#    driverClassName: org.postgresql.Driver
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://localhost:5432/eighteen?currentSchema=love
    username: postgres
    password: 123456
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379