spring:
  active: prd

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: FALSE # 逻辑已删除值(默认为 1)
      logic-not-delete-value: TRUE # 逻辑未删除值(默认为 0)